# Generated by Django 3.1.1 on 2020-09-02 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pilot_program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_at', models.DateField()),
                ('complete', models.BooleanField(default=False)),
                ('pilot_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pilot_program.pilotprogram')),
            ],
        ),
    ]
